name = "nextmetro"
main = "src/index.js"
compatibility_date = "2026-03-01"

routes = [
  { pattern = "nextmetro.live", custom_domain = true },
  { pattern = "www.nextmetro.live", custom_domain = true },
]

[assets]
directory = "./public"
